### ISSUE TITLE
TODO Práctica 5

### ISSUE THREAD

**Issue by germanfr** [ggrupo/ataxx#3]
- [x] Parent Swing View
- [x] Control panel
- **Other Swing views**:
  - [x] Ataxx
  - [x] Connect N
  - [x] Tic Tac Toe
  - [x] Advanced Tic Tac Toe
- **Code improvements**:
  - [x] Add invoke laters when calling view from model and viceversa.
  - [x] **Add comments everywhere.**
  - [x] Fix textarea null pointer exception.
  - [x] Create Ataxx, ~~ConnectN,~~ TicTacToe and Advanced TTT extended factories.

> Control panel visual example: [control_panel.zip](https://github.com/ggrupo/ataxx/files/196506/conrtol_panel.zip)
